<div class="row">
	
  <?php echo $this->render('profile/index/menu.phtml'); ?>
  
  <div class="col-lg-9 col-md-9 col-sm-12">
  	<div class="panel panel-default">
    	<div class="panel-heading">
      	<h4 class="panel-title">
        	<i class="fa fa-cubes" aria-hidden="true"></i> 
          Các hoạt động
       	</h4>
      </div>
			<div class="panel-body">
				<div class="table-responsive">
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th>STT</th>
                <th>Giá</th>
                <th>Nội dung</th>
                <th>Ngày tạo</th>
              </tr>
            </thead>
            <tbody>
            	<?php foreach ($aComment as $key => $item) : ?>
            	<tr>
                <th scope="row"><?php echo ++$key;?></th>
                <td><?php echo $item->price;?></td>
                <td><?php echo $item->comment_content;?></td>
                <td>
                	<?php 
										$sCreateDate = new \DateTime($item->create_date);
										echo $sCreateDate->format('H:i d-m-Y');
									?>
                </td>
              </tr>
            	<?php endforeach; ?>
            </tbody>
          </table>
        </div>
        
        <!-- paging -->
        
      </div>
 		</div>
    
  </div>
</div>