<div class="col-lg-3 col-md-3 col-sm-12">
 
  <div class="panel panel-default">
  
    <div class="panel-heading">
      <h4 class="panel-title">Trang cá nhân</h4>
    </div>
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked tree">
        <li class="active">
          <a href="/profile"> 
            <i class="fa fa-user" aria-hidden="true"></i>
            Thông tin tài khoản 
          </a>
        </li>
        <li>
          <a href="/profile/posting"> 
            <i class="fa fa-adn" aria-hidden="true"></i>
            Tin mua bán 
          </a>
        </li>
        <li>
          <a href="/profile/activities"> 
            <i class="fa fa-cubes" aria-hidden="true"></i>
            Các hoạt động 
          </a>
        </li>
        <li>
          <a href="/profile/notification"> 
            <i class="fa fa-bell" aria-hidden="true"></i>
            Thông báo 
          </a>
        </li>
      </ul>
    </div>
    
  </div>

</div>