<div class="row">  
  <div class="col-md-12">
  	<div class="panel panel-default">
			<div class="panel-body">
      
        <div class="row">
          <div class="col-md-12">
          	<h2 class="section-title">Thông tin liên hệ</h2>
            <hr />
          </div>
          
          <div class="col-md-12">
            <section>
              <form class="form-horizontal" method="post">
              	<?php if ( !empty($sAct) ) : ?>
              	<div class="form-group has-success">
                	<div class="col-md-offset-2 col-md-10">
                		Thông tin của bạn đã được gửi.
                	</div>
                </div>
                <?php endif; ?>
                <div class="form-group">
                	<label class="control-label col-md-2">
                  	<font color="#FF0000">*</font>
                  	Họ tên
                	</label>
                  <div class="col-md-5">
                		<?php 
											echo $this->formInput($oForm->get('fullname'));
            					echo $this->formElementErrors($oForm->get('fullname'), array('class' => 'help-block inline error')); 
            				?>
                 	</div>
                </div>
                <div class="form-group">
                	<label class="control-label col-md-2">
                  	<font color="#FF0000">*</font>
                    Email
                 	</label>
                  <div class="col-md-5">
                		<?php 
											echo $this->formInput($oForm->get('email'));
            					echo $this->formElementErrors($oForm->get('email'), array('class' => 'help-block inline error')); 
            				?>
                	</div>
                </div>
                <div class="form-group">
                	<label class="control-label col-md-2">
                  	<font color="#FF0000">*</font>
                    Nội dung
                 	</label>
                  <div class="col-md-8">
                		<?php 
											echo $this->formTextarea($oForm->get('content'));
            					echo $this->formElementErrors($oForm->get('content'), array('class' => 'help-block inline error')); 
            				?>
                 	</div>
                </div>
               
                <div class="form-group">
                  <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default"> Gửi </button>
                  </div>
                </div>
              </form>
            </section>
          </div>
        </div>
    
			</div>
		</div>
	</div>
</div>