<div class="page-content">
	<div class="row">
    <div class="col-xs-12">
    	<div class="page-header">
        <h1><?php echo $this->translate('Get Coordinates'); ?></h1>
      </div>
      
      <form method="post" class="form-horizontal">
      
      	<div class="form-group">
        	<label class="col-xs-2 control-label no-padding-right"> 
						<?php echo $this->translate('Name'); ?>: 
         	</label>
          <div class="col-xs-10">
            <p class="form-control-static"><?php echo $infoData['name'] ?></p>
          </div>
        </div>
        	
        <div class="form-group">
        	<label class="col-sm-2 control-label no-padding-right"> 
          	<b class="red">*</b> 
						<?php echo $this->translate('Position'); ?>: 
         	</label>
          <div class="col-xs-10 col-sm-8 col-md-6 col-lg-4">
            <div class="input-group">
              <input type="text" value="<?php echo $infoData['position'] ?>" class="form-control" name="position" id="position"/>
              <a href="javascript:;" class="input-group-addon" onClick="codeAddress()">
                <?php echo $this->translate('Get Coordinates'); ?>
              </a>
            </div>
          </div>
        </div>
        
        <div class="form-group">
        	<label class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Coordinates'); ?>: </label>
          <div class="col-sm-10">
						<input type="text" value="<?php echo $infoData['latitude'] ?>" name="latitude" id="latitude">
            <input type="text" value="<?php echo $infoData['longitude'] ?>" name="longitude" id="longitude">
          </div>
        </div>
        
        <div class="form-group">
        	<div class="col-sm-offset-2 col-sm-10">
						<div id="map" style="height:300px;"></div>
          </div>
        </div>

        <div class="clearfix form-actions">
          <div class="col-sm-offset-2 col-sm-10">
          	<button type="submit" class="btn btn-info">
          		<i class="ali-icon fa fa-check bigger-110"></i>
          		Save
          	</button>
          </div>
        </div>
      </form>
  	</div>
	</div>
</div>

<script>
$( document ).ready(function() {
  //codeAddress();
});

function initAutocomplete() {
  var input = document.getElementById('position');
  var searchBox = new google.maps.places.SearchBox(input);
}

function codeAddress() {
	geocoder = new google.maps.Geocoder();
	var address = document.getElementById("position").value;
	geocoder.geocode( { 'address': address}, function(results, status) {
		if (status == google.maps.GeocoderStatus.OK) {
			var lat = results[0].geometry.location.lat();
			document.getElementById("latitude").value = lat;
			var lng = results[0].geometry.location.lng();
			document.getElementById("longitude").value = lng;
			
			var location = {lat: lat, lng: lng};

			var map = new google.maps.Map(document.getElementById('map'), {
				scaleControl: true,
				center: location,
				zoom: 15
			});
		
			var marker = new google.maps.Marker({map: map, position: location});
			marker.addListener('click', function() {
				infowindow.open(map, marker);
			});
			
		} 
		else {
			alert("Geocode was not successful for the following reason: " + status);
		}
	});
}

function geolocate() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var geolocation = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };
      var circle = new google.maps.Circle({
        center: geolocation,
        radius: position.coords.accuracy
      });
      autocomplete.setBounds(circle.getBounds());
    });
  }
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&callback=initAutocomplete"></script>
