<div class="page-content">
	<div class="row">
    <div class="col-xs-12"> 
      <div class="table-header">Location
      	<div class="pull-right">
          <a href="/admin/location/add" title="Thêm" class="btn btn-info btn-sm bigger-100">
            <i class="fa fa-plus"></i> Thêm
         	</a>
      	</div>
      </div>
      
      <div>
        <div class="dataTables_wrapper form-inline no-footer">
          <table class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
              <tr>
                <th class="center">No.</th>
                <th class="center">ID</th>
                <th>Name</th>
                <th class="center">Status</th>
                <th class="center">Operation</th>
              </tr>
            </thead>
  
            <tbody>
              <?php foreach ($aResult as $key => $item) : ?>
              <tr>
              	<td class="center"><?php echo $key + 1;?></td> 
                <td class="center"><?php echo $item->id;?></td>
                <td>
                	<?php if ($item->parent == 0): ?>
                    <a href="/admin/location?parent=<?php echo $item->id;?>">
                      <?php echo $item->name;?>
                    </a>
                	<?php else: ?>
                  	<?php echo $item->name;?>
                  <?php endif; ?>
              	</td>
                <td class="center">
                  <a href="javascript:;" onclick="updateStatus(<?php echo $item->id;?>, '<?php echo $item->isactive;?>')">
                  	<?php if ( isset($aIsActive[$item['isactive']]) ) : ?>
                  		<?php echo $aIsActive[$item['isactive']];?>
                 		<?php endif; ?>
                	</a>
                </td>
                <td class="center">
                	<a href="/admin/location/edit?id=<?php echo $item->id;?>" title="Edit">
                  	<i class="ali-icon fa fa-pencil bigger-130"></i>
                  </a>
                </td>               
              </tr>
              <?php endforeach; ?>  
            </tbody>
          </table>
          
        </div>
      </div>
        
    </div><!-- /.col -->
  </div><!-- /.row -->

</div>

<script>
function updateStatus(id, status)
{
	$.ajax({
		url: "/admin/location/update-status",
		method: "POST",
		data: {id: id, status: status},
		dataType:"html"
	}).done(function(data) {
		location.reload(); 
	});
}
</script>
