<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php echo $this->headTitle($this->sHeaderTitle); ?>
       
		<?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
	<meta name="google-site-verification" content="r8hW3eDmd4rvVggPLtcQH8RnWj9xsb2TsMKYTfkqKLc" />
    <link rel="alternate" hreflang="vi-vn" href="<?php echo $this->serverUrl(true); ?>">
    
    <meta name="description" content="<?php echo $this->sSiteDescription; ?>"/>
    <meta name="keywords" content="<?php echo $this->sSiteKeywords; ?>" >

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                    //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
          
		<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-67552021-1', 'auto');
      ga('send', 'pageview');
    </script>

	</head>
    
	<body>
  
  	<div role="navigation" class="navbar navbar-tshop navbar-fixed-top megamenu">
			<div class="container">
        <div class="navbar-header">	
          <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
            <span class="sr-only"> Toggle navigation </span> 
            <span class="icon-bar"> </span> 
            <span class="icon-bar"> </span> 
            <span class="icon-bar"> </span>
          </button>
          <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
            <i class="fa fa-home"></i> Trang chủ
         	</a>
        </div>
 
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li <?php if ($this->menu == 'vip') : ?>class="active"<?php endif; ?>>
            	<a href="/can-ho-cao-cap"> Căn hộ cao cấp </a>
          	</li>
            <li <?php if ($this->menu == 'intermediate') : ?>class="active"<?php endif; ?>>
            	<a href="/can-ho-trung-cap"> Căn hộ trung cấp </a>
           	</li>
            <li class="dropdown">
            	<a href="/posting" class="dropdown-toggle" data-toggle="dropdown"> Tin mua bán <b class="caret"> </b> </a>
              <ul class="dropdown-menu">
              	<li><a href="/posting?type=1"> Bán căn hộ </a></li>
                <li class="divider"></li>
                <li><a href="/posting?type=2"> Cho thuê căn hộ </a></li>
                <li class="divider"></li>
                <li><a href="/posting?type=3"> Mua căn hộ </a></li>
                <li class="divider"></li>
                <li><a href="/posting?type=4"> Thuê căn hộ </a></li>
              </ul>
          	</li>
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <?php if ( isset($infoAccount['account_id']) ) : ?>
              <li>
                <a href="/profile"><?php echo $infoAccount['fullname']; ?></a>
              </li>  
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#"><i class="fa fa-key"></i> Đổi mật khẩu</a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="/logout"><i class="fa fa-power-off"></i> Thoát</a>
                  </li>
                </ul>
              </li>
            <?php else : ?>
            	<li>
                <a href="<?php echo $this->url('login') ?>">Đăng nhập</a>
              </li>
              <li>
                <a href="<?php echo $this->url('register') ?>">Đăng ký</a>
              </li>
            <?php endif; ?>
            <li class="postadd">
            	<a href="/profile/posting/add" class="btn btn-info button-block">
              	<i class="fa fa-check"></i> Đăng tin
             	</a>
           	</li>   		
          </ul>
        </div>

			</div>

		</div>
    
    
    
    
    
    
    
   	<!--
    <div role="navigation" class="navbar navbar-tshop navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="<?php echo $this->url('home') ?>" class="navbar-brand ">
            Định giá căn hộ
          </a>
        </div>
    
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li <?php if ($this->menu == 'vip') : ?>class="active"<?php endif; ?>>
              <a href="/can-ho-cao-cap">Căn hộ cao cấp</a>
            </li>
            <li <?php if ($this->menu == 'intermediate') : ?>class="active"<?php endif; ?>>
              <a href="/can-ho-trung-cap">Căn hộ trung cấp</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <?php if ( isset($infoAccount['account_id']) ) : ?>
              <li>
                <a href="/profile"><?php echo $infoAccount['fullname']; ?></a>
              </li>  
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#"><i class="fa fa-key"></i> Đổi mật khẩu</a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="/logout"><i class="fa fa-power-off"></i> Thoát</a>
                  </li>
                </ul>
              </li>
            <?php else : ?>
              <li>
                <a href="<?php echo $this->url('register') ?>">Đăng ký</a>
              </li>
            <?php endif; ?>   		
          </ul>
        </div>
      </div>
    </div>
    
    -->
        
    <div class="container">
			<?php echo $this->content; ?>
      
      <footer>
        <p>
          <a href="/gioi-thieu">Giới thiệu</a> 
          - 
          <a href="/quyen-rieng-tu">Quyền riêng tư</a> 
          - 
          <a href="/dieu-khoan">Điều khoản</a> 
          - 
          <a href="/lien-he">Liên hệ</a>
        </p>
        <p>Dinhgiacanho.vn &copy; 2005</p>
      </footer>
    </div> 
    
    <div class="container" role="modal">
      <div class="row">
      	<div class="col-sm-12">
        
          <div class="modal" id="modal-account-login" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                  </button>
                  <h4 class="modal-title">Đăng nhập để xem nội dung này</h4>
                </div>
                <div class="modal-body" align="center">
                  <a class="btn btn-primary" href="/login?back_url=<?php echo urlencode($this->serverUrl(true)); ?>">Đăng nhập</a> 
                  <a class="btn btn-primary" href="/register">Đăng ký</a>
                </div>
              </div>
            </div>
          </div>
          
      	</div>
    	</div>
   	</div> 
    
		<?php echo $this->inlineScript()->prependFile($this->basePath('js/common.js')) ?>
	</body>
</html>
