<?php
$strRequestUri = '';
if ( isset($this->request_uri) && count($this->request_uri) > 0 ) {
	foreach ($this->request_uri as $key => $value) {
		if ( !empty($value) ) {
			$strRequestUri = $strRequestUri .'&'. $key .'='. $value;
		}
	}
}
?>


<?php if ($this->pageCount): ?>
<ul class="pagination">
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
		<li>
			<a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous . $strRequestUri;?>">Previous</a>
		</li>
	<?php endif; ?>
	
	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
		<?php if ($page != $this->current): ?>
			<li>
				<a href="<?php echo $this->url($this->route );?>?page=<?php echo $page . $strRequestUri; ?>"> 
					<?php echo $page; ?>
				</a>
			</li>
		<?php else: ?>
			<li class="active">
				<a href="javascript:;"><?php echo $page; ?></a>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
	
	
	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
		<li>
			<a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next . $strRequestUri; ?>">Next</a>
		</li>
	<?php endif; ?>
	
</ul>
<?php endif; ?>
  	