<div class="page-content">
	<div class="row">
    <div class="col-xs-12"> 
      <div class="table-header">Group List
      	<div class="pull-right">
          <a href="/admin/group/add" title="Add" class="btn btn-info btn-sm bigger-100">
            <i class="fa fa-plus"></i> Add
         	</a>
      	</div>
      </div>
      
      <div>
        <div class="dataTables_wrapper form-inline no-footer">
          <table class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
              <tr>
                <th class="center">No.</th>
                <th class="center">ID</th>
                <th>Name</th>
                <th class="center">Operation</th>
              </tr>
            </thead>
  
            <tbody>
              <?php foreach ($aResult as $key => $item) : ?>
              <tr>
              	<td class="center"><?php echo $key + 1;?></td> 
                <td class="center"><?php echo $item->group_id;?></td>
                <td><?php echo $item->group_name;?></td>
                <td class="center">
                	<a href="/admin/group/edit?id=<?php echo $item->group_id;?>" title="Edit">
                  	<i class="ali-icon fa fa-pencil bigger-130"></i>
                  </a>
                </td>               
              </tr>
              <?php endforeach; ?>  
            </tbody>
          </table>
          
        </div>
      </div>
        
    </div><!-- /.col -->
  </div><!-- /.row -->

</div>