<div class="row">
	<div class="col-lg-9 col-md-9 col-sm-12">
  	<div class="panel panel-default">
			<div class="panel-body">
      	<h2><?php echo $infoPosting->title; ?></h2>
        <hr>
         Khu vực: Bán nhà riêng tại Đường Tỉnh Lộ 10 - Huyện Bình Chánh - Hồ Chí Minh <br>
				Giá: 1.2 Tỷ Diện tích: 300 m² <br>
				Dự án : 
      </div>
  	</div>
 	</div>
  
  <div class="col-lg-3 col-md-3 col-sm-12">
  
  </div>
</div>