<div class="row">
	<div class="col-lg-9 col-md-9 col-sm-12">
  	<div class="panel panel-default">
			<div class="panel-body">
      	<?php foreach ($aPosting as $index => $posting) : ?>
        <div class="media">
          <div class="media-left col-sm-3">
            <a href="#">
              <img class="img-responsive" src="/upload/2016/01/49/logo.jpg" alt="">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
            	<a href="<?php echo $this->PostingUrl($posting->id, $posting->title); ?>">
            		<?php echo $posting->title; ?>
            	</a>
            </h4>
            <div></div>
            
          </div>
        </div>
        <hr>
        <?php endforeach; ?> 
        
        
    	</div>
      
      <div class="panel-footer">
      	 <div class="row">
        	<div class="col-xs-12 text-center">
          	<?php
							echo $this->paginationControl(            	
								$this->aPosting,
								'sliding',
								array('layout/paginator.phtml', 'Apartment'),
								array(
									'route' => 'posting',
									//'request_uri' => $aSearch
								)
							);
						?>  
          </div>
        </div>
      </div>
      
  	</div>
    
  </div>
  
  <div class="col-lg-3 col-md-3 col-sm-12">
  
  </div>
</div>