<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle('Content Management System - Định giá căn hộ'); ?>

  <?php echo $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                  ->prependStylesheet($this->basePath() . '/css/backend.css')
									->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

  <!-- Scripts -->
  <?php echo $this->headScript()
      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
      ->prependFile($this->basePath() . '/js/jquery.min.js')
      ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
      ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
  ; ?>

</head>
<body>
    <div id="navbar" class="navbar navbar-default">
			<div class="navbar-container" id="navbar-container">
				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
					<span class="sr-only">Toggle sidebar</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<div class="navbar-header pull-left">
					<a href="<?php echo $this->url('admin'); ?>" class="navbar-brand">
						<small>Định giá căn hộ - Administrator System</small>
					</a>
				</div>

				<div class="navbar-buttons navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">
						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<span class="user-info">
									<?php echo $this->infoAdminUser->fullname; ?>
								</span>
								<i class="ace-icon fa fa-caret-down"></i>
							</a>

							<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
								<li>
									<a href="/admin/change-password">
										<i class="ace-icon fa fa-key"></i>
										Change password
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="/admin/logout">
										<i class="ace-icon fa fa-power-off"></i>
										Logout
									</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div><!-- /.navbar-container -->
		</div>
  	<div class="main-container" id="main-container">
			<div id="sidebar" class="sidebar responsive">
				

				<ul class="nav nav-list">
        	<li class="open">
						<a class="dropdown-toggle" href="#">
							<i class="menu-icon fa fa-tasks"></i>
							<span class="menu-text">
								Administrator
							</span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu nav-show" style="display: block;">
							<li <?php if ($this->sMenuLevel2 == 'user'): ?>class="active"<?php endif;?> >
								<a href="/admin/user">
									<i class="menu-icon fa fa-caret-right"></i>
									Users
								</a>

								<b class="arrow"></b>
							</li>

							<li <?php if ($this->sMenuLevel2 == 'group'): ?>class="active"<?php endif;?> >
								<a href="/admin/group">
									<i class="menu-icon fa fa-caret-right"></i>
									Group
								</a>
								<b class="arrow"></b>
							</li>
							
						</ul>
					</li>
          
          <li <?php if ($this->sMenu == 'location'): ?>class="active"<?php endif;?>>
						<a href="/admin/location">
							<i class="menu-icon fa fa-map-marker"></i>
							<span class="menu-text"> Location </span>
						</a>
					</li>
          
          <li <?php if ($this->sMenu == 'apartment'): ?>class="active"<?php endif;?>>
						<a href="/admin/apartment">
							<i class="menu-icon fa fa-home"></i>
							<span class="menu-text"> Apartment </span>
						</a>
					</li>
          
          <li <?php if ($this->sMenu == 'commment'): ?>class="active"<?php endif;?>>
						<a href="/admin/comment">
							<i class="menu-icon fa fa-commenting"></i>
							<span class="menu-text"> Comment </span>
						</a>
					</li>
          
          <li <?php if ($this->sMenu == 'contact'): ?>class="active"<?php endif;?>>
						<a href="/admin/contact">
							<i class="menu-icon fa fa-envelope"></i>
							<span class="menu-text"> Contact </span>
						</a>
					</li>
          
          <li class="">
						<a href="javascript:;" onClick="showFileManagement()">
							<i class="menu-icon fa fa-upload"></i>
							<span class="menu-text"> Upload Management </span>
						</a>
					</li>
          	
				</ul><!-- /.nav-list -->

				<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
					<i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
				</div>
        
        <script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
			</div>

			<div class="main-content">
				<div class="main-content-inner">
          <?php echo $this->content; ?>
				</div>
			</div><!-- /.main-content -->

			<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Định Giá Căn Hộ</span>
							Application &copy; 2015
						</span>
					</div>
				</div>
			</div>

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div>
    
	<div class="modal fade" id="modal-file-management">
  	<div class="modal-dialog modal-lg">
  		<div class="modal-content">
  			<div class="modal-header">
  				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  				<h4 class="modal-title">Upload Management</h4>
  			</div>
  			<div class="modal-body" id="page-file-management"></div>
  			<div class="modal-footer">
  				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  			</div>
  		</div>
  	</div>
  </div>
      
	<?php 
		echo $this->inlineScript()
												->prependFile($this->basePath() . '/js/ace/elements.scroller.js')
												->prependFile($this->basePath() . '/js/ace.js');
	?>
	
	<script type="text/javascript">
		function showFileManagement(){	
			$('#modal-file-management').modal();
			$.ajax({
				url: "/admin/file-management",
				method: "GET",
				dataType:"html"
			}).done(function(data) {
				$('#page-file-management').html(data); 
			});
		}
	</script>
</body>
</html>
