<div class="row">  
  <div class="col-md-12">
  	<div class="panel panel-default">
			<div class="panel-body">
      	<h3 class="title-big text-center">Về chúng tôi</h3>
        <hr />
        <p>
        	<strong>Dinhgiacanho</strong> cung cấp thông tin các căn hộ mà khách hàng quan tâm.
        </p>
        <p>
        	Mục tiêu của <strong>Dinhgiacanho</strong> là chia sẽ các thông tin từ khách hàng đến khách hàng. Để khách hàng tiếp cận căn hộ với đầy đủ thông tin nhất có thể. 
        </p>
        <p>
        	Mọi thông tin trên website chỉ có tính tham khảo với khách hàng.
        </p>
        <p style="text-align:justify">
					<strong>Các dịch vụ chính</strong>:<br>
					- Đăng thông tin các dự án căn hộ<br>
					- Đăng tin mua, bán, cho thuê các căn hộ<br>
      	</p>
      </div>
  	</div>
 	</div>
</div>