<div class="row">  
  <div class="col-md-12">
  	<div class="panel panel-default">
			<div class="panel-body">
      
      	<div class="page-login">
          <h2 class="block-title"> <i class="fa fa-sign-in"></i> Đăng nhập </h2>
          <hr />
          <form method="post">
          	<div class="form-group">
            	<label>Email</label>
              <input type="email" name="email" class="form-control" placeholder="Email">	
          	</div>
            <div class="form-group">
              <label>Mật khẩu</label>
              <input type="password" name="password" class="form-control" placeholder="Mật khẩu">
          	</div>
            <div class="form-group form-actions">
              <button class="btn btn-primary btn-block btn-lg" type="submit">
                <i class="fa fa-sign-in"></i> Đăng nhập
              </button>
          	</div>
          </form>
          <div>
            <hr />
            <a class="btn pull-right" href="/register">Đăng ký</a>
            <a class="btn " href="#">Quên mật khẩu</a>
          </div>
      	</div>
    
			</div>
		</div>
	</div>
</div>