<div class="row">  
  <div class="col-md-12">
  	<div class="panel panel-default">
			<div class="panel-body">
        <h3 class="title-big text-center">Quyền riêng tư</h3>
        <hr />
        <p>
        - Thông tin cá nhân của thành viên trên website dinhgiacanho.vn được chúng tôi cam kết bảo mật tuyệt đối theo chính sách bảo vệ thông tin cá nhân của dinhgiacanho.vn. Việc thu thập và sử dụng thông tin của mỗi thành viên chỉ được thực hiện khi có sự đồng ý của khách hàng đó trừ những trường hợp pháp luật có quy định khác.
     		</p>
        <p>
					- Không sử dụng, không chuyển giao, cung cấp hay tiết lộ cho bên thứ 3 nào về thông tin cá nhân của thành viên khi không có sự cho phép đồng ý từ thành viên.
      	</p>
				<p>
					- Ban quản trị website dinhgiacanho.vn yêu cầu các cá nhân khi đăng ký là thành viên, phải cung cấp đầy đủ thông tin cá nhân có liên quan như: Họ và tên, địa chỉ liên lạc, email… và chịu trách nhiệm về tính pháp lý của những thông tin trên. Ban quản lý website dinhgiacanho.vn không chịu trách nhiệm cũng như không giải quyết mọi khiếu nại có liên quan đến quyền lợi của Thành viên đó nếu xét thấy tất cả thông tin cá nhân của thành viên đó cung cấp khi đăng ký ban đầu là không chính xác.
     		</p>

			</div>
		</div>
	</div>
</div>