
<div class="row">  
  <div class="col-md-12">
  	<div class="panel panel-default">
			<div class="panel-body">

        <div class="page-register">
          <h2 class="block-title"> <i class="fa fa-user"></i> Đăng ký tài khoản </h2>
          <hr />
          <form method="post">
            <div class="form-group">
              <label>Họ tên</label>
              <?php 
                echo $this->formInput($oForm->get('fullname')); 
                echo $this->formElementErrors($oForm->get('fullname'), array('class' => 'help-block inline error')); 
              ?>
            </div>
            <div class="form-group">
              <label>Địa chỉ Email</label>
              <?php 
                echo $this->formInput($oForm->get('email'));
                echo $this->formElementErrors($oForm->get('email'), array('class' => 'help-block inline error'));
              ?>
            </div>
            <div class="form-group">
              <label>Mật khẩu</label>
              <?php echo $this->formInput($oForm->get('password')) ?>
            </div>
            <div class="form-group form-actions">
              <button class="btn btn-primary btn-block btn-lg" type="submit">
                <i class="fa fa-user"></i> Tạo tài khoản
              </button>
          	</div>
          </form>
        </div>
			
      
      
      </div>
   	</div>
	</div>
</div>