<div class="row">  
  <div class="col-md-12">
  	<div class="panel panel-default">
			<div class="panel-body">
				<h3>Điều Khoản Sử Dụng</h3>

				<p>TIÊU CHÍ, QUYỀN & TRÁCH NHIỆM CỦA THÀNH VIÊN CỦA WEBSITE DINHGIACANHO.VN:</p>
				<p>
          Website dinhgiacanho.vn là sân chơi chung cho mọi người muốn tìm hiểu về căn hộ muốn sinh sống trong tương lai. <br />
          Bản nội quy này được thông báo công khai đến mọi người và là căn cứ để xử lý và giải quyết thắc mắc của thành viên. <br />
          Bài viết vi phạm có thể được chỉnh sửa, xóa, và thành viên sẽ bị xử lý… mà không cần thông báo trước. <br />
          Ban Quản Trị có quyền sử dụng bài viết của thành viên trong phạm vị website dinhgiacanho.vn. <br />
          Nội dung của nội quy có thể thay đổi bất cứ lúc nào mà không cần báo trước. <br />
          Thành viên phải chịu tránh nhiệm về nội dung bài viết của mình. Dinhgiacanho.com sẽ cung cấp những thông tin cần thiết cho cơ quan chức năng khi được yêu cầu. <br />
          Dinhgiacanho.com không chịu trách nhiệm về bất cứ thiệt hại gây ra trực tiếp hay gián tiếp từ các bài viết, nội dung trên Diễn đàn. <br />
          Dinhgiacanho.com ngăn cấm và không chịu bất cứ trách nhiệm nào về bản quyền của các nội dung chia sẻ trên toàn bộ Diễn đàn. <br />
          Dinhgiacanho.com không cho phép sử dụng thương hiệu "Định giá căn hộ", "Dinhgiacanho.vn" trong bất cứ trường nào khi chưa được BQT Tinh tế cho phép.
    	</p>

			<h4>NỘI QUY</h4>
			<p>- Tất cả các nội dung, hình ảnh và tài liệu ở Diễn đàn Tinh tế yêu cầu:</p>
			<p>
        KHÔNG vi phạm luật pháp nước CHXHCN Việt Nam <br />
        KHÔNG vi phạm thuần phong mỹ tục Việt Nam <br />
        KHÔNG liên quan đến chính trị, tôn giáo. <br />
        KHÔNG liên quan đến H A C K, C R A CK, bẻ khóa, nội dung vi phạm bản quyền, phần mềm hay bài viết Kiếm tiền, Kiếm gift card trên mạng. <br />
        KHÔNG gửi các nội dung (bài viết, hình ảnh, âm thanh, video,...) liên quan đến đồi truỵ, khoả thân, 18+. Trường hợp ảnh Nude art do tác giả tự chụp hoặc hoặc các tư liệu khoa học, giáo dục đặc biệt cần phải được BQT duyệt trước khi đăng. <br />
        KHÔNG được share các tài khoản fshare, megashare, tenlua, itunes, mediafire công khai hoặc chưa được BQT cho phép.
        KHÔNG đả kích lẫn nhau. <br />
        KHÔNG được đăng ký định danh (nick, username) trùng với các Điều hành viên, Quản trị viên hay cố tình đăng ký nick trùng với thành viên khác dưới mọi hình thức, kỹ thuật.
        Thành viên KHÔNG được đăng ký hơn 01 định danh (nick, username) trên Diễn đàn, không tạo nick kiểu abc1,abc2,abc3. Định danh không được phép bao gồm các ký tự không thấy hay ẩn đi. <br />
        Thành viên KHÔNG được copy/gửi bài hàng loạt từ các website, diễn đàn khác về gửi trong Diễn đàn. <br />
        PHẢI giữ gìn sự trong sáng của tiếng Việt, gõ tiếng Việt có dấu, không viết nhịu tiếng Việt, hạn chế tối đa sử dụng tiếng nước ngoài. Không được sử dụng toàn chữ viết HOA trong tiêu đề và nội dung bài viết.
    	</p>

			<p>- Quy định về bài viết:</p>
			
      <p>
    		Không spam bài, up bài ngoài khu vực mua bán. <br />
    		Không gửi bài với nội dung vô nghĩa, bóc tem, xé tem, tem,... <br />
    		Không gửi một nội dung ở nhiều nơi. <br />
    		Không chửi nhau, xúc phạm nhau. <br />
    		Trước khi viết bài vui lòng xem qua diễn đàn xem đã đề cập chưa. <br />
    		Nội dung tiêu đề, bài viết phải rõ ràng, nghiêm túc. <br />
    		Không được chia sẻ, phổ biến nội dung vi phạm bản quyền, các phần mềm cr@ck, ha@ck, key phần mềm, và cũng không được đăng bài xin các nội dung này. <br />
    		Khi muốn cám ơn người gởi bài, chỉ cần nhấn nút lệnh “Thích". <br />
    		Bài trả lời không lạc đề, phải có tính xây dựng, nội dung rõ ràng. <br />
    		Thành viên Không được tự ý gửi bài viết có nội dung Khuyến mãi, Khuyến mại, hổ trợ khách hàng tại tất cả các khu vực trên Diễn đàn mà chưa được phép của Ban Quản Trị. Tất cả các bài thuộc loại này muốn đưa lên Diễn đàn hay trang tin thành viên phải liên hệ với Ban Quản Trị để được hổ trợ, xử lý. <br />
    Các bài viết về góp ý, thắc mắc, cảnh báo hoặc xây dựng thương gia vui lòng không gửi tại các khu vực thảo luận của dinhgiacanho.vn.
    		</p>
			</div>
		</div>
	</div>
</div>