<div class="page-content">
	<div class="row">
    <div class="col-xs-12"> 
      <div class="table-header">
      	Comment
    	</div>
      
      <div>
        <div class="dataTables_wrapper form-inline no-footer">
          <table class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
              <tr>
                <th class="center">No.</th>
                <th class="center">Price</th>
                <th>Content</th>
                <th>User</th>
                <th class="center">Create Date</th>
                <th class="center">Operator</th>
              </tr>
            </thead>
  
            <tbody>
              <?php foreach ($paginator as $item) : ?>
              <tr>
              	<td class="center"><?php echo ++$iOffset;?></td> 
                <td class="center"><?php echo $item->price;?></td>
                <td><?php echo $item->comment_content;?></td>
                <td><?php echo $item->fullname;?></td>
                <td class="center">
                	<?php 
										$sCreateDate = new \DateTime($item->create_date);
										echo $sCreateDate->format('d-m-Y');
                	?>
                </td>
                <td class="center">
                	<a href="javascript:;" title="Delete">
                  	<i class="ali-icon fa fa-trash bigger-130"></i>
                  </a>
                </td>               
              </tr>
              <?php endforeach; ?>  
            </tbody>
          </table>
          <div class="row">          	
            <div class="col-sm-12">
							<?php
								echo $this->paginationControl(            	
									$this->paginator,
									'sliding',
									array('layout/paginator.phtml', 'admin'),
									array(
										'route' => 'admin/comment',
									)
								);
              ?>  
          	</div>
        	</div>
          
        </div>
      </div>
        
    </div><!-- /.col -->
  </div><!-- /.row -->

</div>
